import styleObjects from "./style_objects";

export default {
  style: {
    form: styleObjects.form,
    title: styleObjects.title,
    subtitle: styleObjects.subtitle,
    inputLabel: styleObjects.inputLabel,
    baseInput1: styleObjects.baseInput1,
    baseInput2: styleObjects.baseInput2,
    baseInput3: styleObjects.baseInput3,
    baseInput4: styleObjects.baseInput4,
    input: styleObjects.input,
    invalidInput: styleObjects.invalidInput,
    placeholder: styleObjects.placeholder,
    error: styleObjects.error,
    baseSubmitButton1: styleObjects.baseSubmitButton1,
    baseSubmitButton2: styleObjects.baseSubmitButton2,
    baseSubmitButton3: styleObjects.baseSubmitButton3,
    baseSubmitButton4: styleObjects.baseSubmitButton4,
    baseSubmitButton5: styleObjects.baseSubmitButton5,
    baseSubmitButton6: styleObjects.baseSubmitButton6,
    baseSubmitButton7: styleObjects.baseSubmitButton7,
    baseSubmitButton8: styleObjects.baseSubmitButton8,
    submitButton: styleObjects.submitButton,
    footnote: styleObjects.footnote,
    stripeElements: styleObjects.stripeElements,
    verticalInputSeparatorHeight: styleObjects.verticalInputSeparatorHeight,
    horizontalInputSeparatorWidth: styleObjects.horizontalInputSeparatorWidth,
    hr: styleObjects.hr
  },
  add: {
    form: "",
    title: "",
    subtitle: "",
    inputLabel: "",
    baseInput1: "",
    baseInput2: "",
    baseInput3: "",
    baseInput4: "",
    input: "",
    invalidInput: "",
    placeholder: "",
    error: "",
    baseSubmitButton1: "",
    baseSubmitButton2: "",
    baseSubmitButton3: "",
    baseSubmitButton4: "",
    baseSubmitButton5: "",
    baseSubmitButton6: "",
    baseSubmitButton7: "",
    baseSubmitButton8: "",
    submitButton: "",
    footnote: "",
    stripeElements: "",
    verticalInputSeparatorHeight: "",
    horizontalInputSeparatorWidth: "",
    hr: ""
  }
};
