import css from "./css/default.css";

export default {
  className: {
    form: "",
    title: "",
    subtitle: "",
    inputLabel: "",
    baseInput1: "",
    baseInput2: "",
    baseInput3: "",
    baseInput4: "",
    input: "",
    invalidInput: "",
    placeholder: "",
    error: "",
    baseSubmitButton1: "",
    baseSubmitButton2: "",
    baseSubmitButton3: "",
    baseSubmitButton4: "",
    baseSubmitButton5: "",
    baseSubmitButton6: "",
    baseSubmitButton7: "",
    baseSubmitButton8: "",
    submitButton: "",
    footnote: "",
    stripeElements: "",
    verticalInputSeparatorHeight: "",
    horizontalInputSeparatorWidth: "",
    hr: ""
  },
  addClassName: {
    form: "",
    title: "",
    subtitle: "",
    inputLabel: "",
    baseInput1: "",
    baseInput2: "",
    baseInput3: "",
    baseInput4: "",
    input: "",
    invalidInput: "",
    placeholder: "",
    error: "",
    baseSubmitButton1: "",
    baseSubmitButton2: "",
    baseSubmitButton3: "",
    baseSubmitButton4: "",
    baseSubmitButton5: "",
    baseSubmitButton6: "",
    baseSubmitButton7: "",
    baseSubmitButton8: "",
    submitButton: "",
    footnote: "",
    stripeElements: "",
    verticalInputSeparatorHeight: "",
    horizontalInputSeparatorWidth: "",
    hr: ""
  }
};
