export default {
  style: {
    mainContainer: {},
    toggleBtnContainer: {},
    toggleBtn: {},
    leftContainer: {},
    shadow: {},
    absSidebar: {},
    contentContainer: {},
    //
    sidebarContainer: {},
    sidebarTitleContainer: {},
    sidebarTitleText: {},
    sidebarMenu: {},
    sidebarUl: {},
    sidebarLi: {},
    sidebarLiSelected: {},
    sidebarMenuItem: {},
    sidebarMenuItemSelected: {},
    sidebarCloseBtnContainer: {},
    sidebarCloseBtn: {},
  },
  addStyle: {
    mainContainer: {},
    toggleBtnContainer: {},
    toggleBtn: {},
    leftContainer: {},
    shadow: {},
    absSidebar: {},
    contentContainer: {},
    //
    sidebarContainer: {},
    sidebarTitleContainer: {},
    sidebarTitleText: {},
    sidebarMenu: {},
    sidebarUl: {},
    sidebarLi: {},
    sidebarLiSelected: {},
    sidebarMenuItem: {},
    sidebarMenuItemSelected: {},
    sidebarCloseBtnContainer: {},
    sidebarCloseBtn: {},
  }
};
